// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaapikcwuknerhgprwaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhYXBpa2N3dWtuZXJoZ3Byd2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjEzMTQsImV4cCI6MjA3MDQ5NzMxNH0.0J7TFoJ2dREZyGWW5T8-Mk8DX0BXgOGOF0YZ6Doef14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});